// Generated by scripts/fingerprints.ts from tests/scenes.ts. Regenerate it only
// for an intended visual change, and say which scenes changed and why.
export const GOLDEN: Record<string, string> = {
  'walk and sit: siamese': '5a03237f',
  'walk and sit: orange': '083ce138',
  'walk and sit: tuxedo': 'cc642614',
  'walk and sit: black': 'e7ab7601',
  'walk and sit: russian-blue': '02881a52',
  'walk and sit: white': '8f0c5c80',
  'walk and sit: calico': 'a6fb3ce6',
  'walk and sit: tortoiseshell': 'dbc16688',
  'yarn': 'e8d15ae3',
  'pounce': 'c0b03f34',
  'reactions': '9aeb5861',
}
