// Generated by scripts/fingerprints.ts from tests/scenes.ts. Regenerate it only
// for an intended visual change, and say which scenes changed and why.
export const GOLDEN: Record<string, string> = {
  'walk and sit: siamese': '5934c74f',
  'walk and sit: orange': '0e4f7f60',
  'walk and sit: tuxedo': '95cd9420',
  'walk and sit: black': '924246e5',
  'walk and sit: russian-blue': '10090022',
  'walk and sit: white': 'd7369cd8',
  'walk and sit: calico': '1345552a',
  'walk and sit: tortoiseshell': '22cde214',
  'yarn': 'e8d15ae3',
  'pounce': 'c0b03f34',
  'reactions': '0a94a42c',
  'halloween: walk and sit': 'b41b8c27',
  'halloween: yarn': '54bd9583',
  'halloween: reactions': 'e6a8d4b1',
}
