// Prints tests/golden.ts: the fingerprint of every golden scene as drawn now.
//   npx tsx scripts/fingerprints.ts > tests/golden.ts
import { fingerprint, SCENES } from '../tests/scenes.ts'

const lines = Object.entries(SCENES).map(([name, scene]) => `  '${name}': '${fingerprint(scene())}',`)
console.log(`// Generated by scripts/fingerprints.ts from tests/scenes.ts. Regenerate it only
// for an intended visual change, and say which scenes changed and why.
export const GOLDEN: Record<string, string> = {
${lines.join('\n')}
}`)
